# A BuildLogParser understands how to parse Test::Unit and RSpec test errors generated by a build
# run and turn them into a more succinct error representation.
class BuildLogParser

  TEST_ERROR_REGEX = /^\s+\d+\) Error:\n(.*):\n(.*)\n([\s\S]*?)\n\n/
  TEST_FAILURE_REGEX = /^Failure:([\S\s]*?)==/

  TEST_NAME_REGEX = /\S+/
  MESSAGE_REGEX = /\: ([\s\S]+)/
  STACK_TRACE_REGEX = /\: [\s\S]+\n(.*)\n/

  def initialize(log)
    @log = log
  end

  def errors
    test_errors
  end

  def test_errors
    test_errors = []

    @log.scan(TEST_ERROR_REGEX) do |match|
      test_errors << TestErrorEntry.create_error($1, $2, $3)
    end

    return test_errors
  end

  def summary
    @log.split("\n").grep(/^RUNNING:|tests,.*skips$/)
  end

  def failures
    test_failures
  end

  def test_failures
    test_failures = []

    @log.scan(TEST_FAILURE_REGEX) do |text|
      content = $1

        test_name = content.match(TEST_NAME_REGEX).to_s
        message = content.match(MESSAGE_REGEX)[1]
        stack_trace = content.match(STACK_TRACE_REGEX)[1]

        test_failures << TestErrorEntry.create_failure(test_name, message, stack_trace)

        # Do Nothing, Pattern does not match

    end

    test_failures
  end

  def failures_and_errors
    failures + errors
  end

end
